# Generated by Django 6.0.6 on 2026-06-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('form', 'order'), name='unique_order_per_form'),
        ),
    ]
